### ISSUE TITLE
Not work with YDB Documents tables

### ISSUE THREAD

**Issue by 1xtr** [AntonShuvaev/intellij-dynamodb#32] opened 2023-04-17 21:00 UTC
In my YC Functions I work with YDB Document tables with `@aws-sdk/client-dynamodb` and `@aws-sdk/lib-dynamodb` libs for all Cmd.
In latest PhpStorm plugin connect successfully but not open tree of content

**Comment by AntonShuvaev** [comment] 2023-04-18 11:17
Thanks for reporting the issue. I will take a look at a it.

**Comment by AntonShuvaev** [comment] 2023-04-20 15:46
The issue is fixed in version 2023.1.5.

**Closed by AntonShuvaev** 2023-04-20 15:46 UTC

**Comment by 1xtr** [comment] 2023-04-20 17:47
All works fine! Thx!
